# Wazuh App Copyright (C) 2019 Wazuh Inc. (License GPLv2)
version: '2'

services:
  wazuh:
    #image: wazuh/wazuh:latest
    build:
      context: ./wazuh
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    depends_on:
      - logstash

  logstash:
    #image: wazuh/wazuh-logstash:latest
    build:
      context: ./logstash
    hostname: logstash
    restart: always
    links:
      - elasticsearch:elasticsearch
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    environment:
      - LS_HEAP_SIZE=2048m

  elasticsearch:
    #image: wazuh/wazuh-elasticsearch:latest
    build: 
      context: ./elasticsearch
    hostname: elasticsearch
    restart: always
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - ELASTIC_CLUSTER=true
      - CLUSTER_NODE_MASTER=true
      - CLUSTER_MASTER_NODE_NAME=es01
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g

  kibana:
    #image: wazuh/wazuh-kibana:latest
    build:
      context: ./kibana
    hostname: kibana
    restart: always
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
      - wazuh:wazuh
  nginx:
    image: wazuh/wazuh-nginx:latest
    hostname: nginx
    restart: always
    environment:
      - NGINX_PORT=443
      - NGINX_CREDENTIALS
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - kibana
    links:
      - kibana:kibana
