
# Wazuh - Filebeat configuration file
filebeat.modules:
  - module: blueliv
    alerts:
      enabled: true
    archives:
      enabled: false

setup.template.json.enabled: true
setup.template.json.path: '/etc/filebeat/blueliv-template.json'
setup.template.json.name: 'blueliv'
setup.template.overwrite: true
setup.ilm.enabled: false

output.elasticsearch.hosts: ['http://elasticsearch:9200']
